In [1]:
#Snowpark lib
from snowflake.snowpark import Session

# Data Science Libs
import numpy as np
import pandas as pd

# create_temp_table warning suppresion
import warnings; warnings.simplefilter('ignore')

In [2]:
from fosforml.model_manager.snowflakesession import get_session
my_session = get_session()

In [3]:
table_name = 'CUSTOMER_DATA_INSIGHT_TRAIN_OUTPUT'

sf_df = my_session.sql("select * from {}".format(table_name))
df = sf_df.to_pandas()

In [4]:
data = pd.read_csv('train_df_insurance.csv')

In [5]:
data.head()

,CUSTOMER_ID,HIGHEST_SPENT,PRODUCT_ID,INSURANCE_NAME,PROCESSING_FEES,COVERAGE_LIMIT,ANNUAL_FEE,ELIGIBLE_LIMIT
0,PNC31d3482a-ba31-42c4-aa7a-27b9d35c3,Cash Transactions,7,Sigma HealthCare,0,5000,100,18
1,PNC28078b5c-7d7e-4d5d-852d-743557151,Health care,4,Criti Care Insurance,0,30000,600,18
2,PNCea940b80-c329-4151-840a-25e1b1152,Travel,1,Annual Trip Insurance,7,1250,145,100
3,PNC1031148a-9223-4144-bc99-2000bfdac,Health care,4,Criti Care Insurance,0,30000,600,18
4,PNC60f353b5-5c34-459f-8766-956fe378b,Health care,6,Figma Preventive Care,0,10000,450,0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CUSTOMER_ID      80000 non-null  object
 1   HIGHEST_SPENT    80000 non-null  object
 2   PRODUCT_ID       80000 non-null  int64
 3   INSURANCE_NAME   80000 non-null  object
 4   PROCESSING_FEES  80000 non-null  int64
 5   COVERAGE_LIMIT   80000 non-null  int64
 6   ANNUAL_FEE       80000 non-null  int64
 7   ELIGIBLE_LIMIT   80000 non-null  int64
dtypes: int64(5), object(3)
memory usage: 4.9+ MB

In [ ]:
ins_train_sf=my_session.createDataFrame(
        data.values.tolist(),
        schema=data.columns.tolist())
ins_train_sf.write.mode("overwrite").save_as_table("FDC_Insurance.INS_CUST_SEGMT_SCHEMA.INSURANCE_CUSTOMER_MAPPING")

In [8]:
insurance = pd.read_csv('Insurance.csv')

In [9]:
insurance

,CARDID,CARDNAME,INTERESTRATE,CREDITLIMIT,ANNUALFEE,REWARDSPROGRAM,INTRODUCTORYAPR,FOREIGNTRANSACTIONFEE,LATEPAYMENTFEE,BALANCETRANSFERFEE,CASHADVANCEFEE,SECURITYDEPOSIT,CARDTYPE
0,1,Admin One SavorOne Cash Rewards Credit Card,15.49,6000,0,Bills and Utilities,0,0.0,39,3,10,0,Unsecured
1,2,Recover Cash bank card,13.99,6000,95,Bills and Utilities,0,2.7,39,5,5,0,Unsecured
2,3,City Double Cash Card,13.99,5000,0,Entertainment,0,3.0,39,5,10,0,Unsecured
3,4,Blue Cash Preferred Card from Express,11.99,5000,0,Entertainment,0,0.0,39,3,10,0,Unsecured
4,5,Customized Cash Rewards credit card,13.99,5000,0,Entertainment,0,3.0,39,3,10,0,Unsecured
5,6,Admin One Quicksilver Cash Rewards Credit Card,15.49,5000,0,Entertainment,0,0.0,39,3,10,0,Unsecured
6,7,Admin One Platinum Secured Credit Card,26.99,200,0,Dinning,0,0.0,39,3,10,200,Secured
7,8,Phase Sapphire Reserve,16.99,10000,550,Dinning,0,0.0,39,5,10,0,Unsecured
8,9,Recover it Miles,11.99,5000,0,Dinning,0,0.0,39,3,10,0,Unsecured
9,10,Phase Freedom Unlimited,14.99,5000,0,Fuel,0,0.0,39,5,10,0,Unsecured
10,11,Fargo Active Cash Card,14.99,7000,0,Fuel,0,0.0,37,5,12,0,Unsecured
11,12,Phase Sapphire Preferred Card,15.99,5000,95,Fuel,0,0.0,39,5,10,0,Unsecured
12,13,Fargo Reflect Card,12.99,5000,0,Fuel,0,0.0,37,5,12,0,Unsecured
13,14,City Diamond Preferred Card,13.74,5000,0,Retail,0,3.0,39,5,10,0,Unsecured
14,15,Admin One Venture Rewards Credit Card,17.24,10000,95,Travel,0,0.0,39,3,10,0,Unsecured
15,16,Bank Altitude Go Signature Card,14.99,5000,0,Travel,0,0.0,39,3,10,0,Unsecured
16,17,Express Gold Card,0.00,0,250,Travel,0,0.0,0,0,0,0,Charge Card
17,18,The Platinum Card from Express,0.00,0,695,Travel,0,0.0,0,0,0,0,Charge Card
18,19,Admin One Travel Rewards Credit Card,15.49,5000,0,Travel,0,0.0,39,3,10,0,Unsecured
19,20,Bank Travel Rewards credit card,13.99,5000,0,Travel,0,0.0,39,3,10,0,Unsecured
20,21,City Miscellaneous Card,14.99,7000,0,Miscellaneous,0,0.0,37,4,10,50,Unsecured

In [10]:
insurance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CARDID                 21 non-null     int64
 1   CARDNAME               21 non-null     object
 2   INTERESTRATE           21 non-null     float64
 3   CREDITLIMIT            21 non-null     int64
 4   ANNUALFEE              21 non-null     int64
 5   REWARDSPROGRAM         21 non-null     object
 6   INTRODUCTORYAPR        21 non-null     int64
 7   FOREIGNTRANSACTIONFEE  21 non-null     float64
 8   LATEPAYMENTFEE         21 non-null     int64
 9   BALANCETRANSFERFEE     21 non-null     int64
 10  CASHADVANCEFEE         21 non-null     int64
 11  SECURITYDEPOSIT        21 non-null     int64
 12  CARDTYPE               21 non-null     object
dtypes: float64(2), int64(8), object(3)
memory usage: 2.3+ KB

In [12]:
ins_train_sf=my_session.createDataFrame(
        insurance.values.tolist(),
        schema=insurance.columns.tolist())
ins_train_sf.write.mode("overwrite").save_as_table("FDC_Insurance.INS_CUST_SEGMT_SCHEMA.INSURANCE_DETAILS")

### Run below query on Snowflake

#### CREATE TABLE CUSTOMER_DATA_INSIGHT_INSURANCE_CATEGORIZE AS
#### SELECT CUSTOMER_ID, DATE, AGE, SEX, EDUCATION_LEVEL,
#### EMPLOYMENT_STATUS, HOBBIES, MARITAL_STATUS, DEPENDENTS,
#### REGISTRATION_DATE, BANK_ACCOUNT_TYPE, BALANCE,
#### BALANCE_FREQUENCY, CREDIT_LIMIT, CASH_ADVANCE,
#### CASH_ADVANCE_FREQUENCY, CASH_ADVANCE_TRX, PURCHASES,
#### ONEOFF_PURCHASES, INSTALLMENTS_PURCHASES, PURCHASES_FREQUENCY,
#### ONEOFF_PURCHASES_FREQUENCY, PURCHASES_INSTALLMENTS_FREQUENCY,
#### PURCHASES_TRX, PAYMENTS, MINIMUM_PAYMENTS, PRC_FULL_PAYMENT,
#### CLUSTER, CLUSTER_TYPE, PREDICTION, REPORT_DATE, CLUSTER_ID
#### FROM FDC_INSURANCE.INS_CUST_SEGMT_SCHEMA.CUSTOMER_DATA_INSIGHT_TRAIN_OUTPUT